### PR TITLE
Add Dodge page and assets

### PR DESCRIPTION
**Pull request by christopher-dodge**
Hi there, this is my first pull request with a team. So, hopefully I did this right. Thanks!

### CODE REVIEW

**Review by ravens-eye — CHANGES_REQUESTED** [review]
The page looks awesome!! Just a couple pathing tweaks to get it to a servable state. 

1. You need to add an entry in the server to serve your dodge.html page.
2. The paths to your css and images should start with /css because the server is set to serve static assets from `/client/assets/` 

See other peoples files for examples :)

Also put .DS_Store in the `.gitignore` file. That's not something that needs to be checked in to git

And nice job on the image file sizes. Gotta keep the user experience slim and fast :+1:

**Comment by ravens-eye** [comment]
To make sure your paths work, run `yarn install` to install the project dependencies, then `yarn start` and navigate to `http://localhost:9001/`

**Comment by christopher-dodge** [comment]
Thank you! I think I've got the revisions nailed down. Do I need to create a new pull request or will the new commit just amend automatically to the original for review?

**Comment by ravens-eye** [comment]
> Thank you! I think I've got the revisions nailed down. Do I need to create a new pull request or will the new commit just amend automatically to the original for review?

The commits are just added !

**Review by ravens-eye — APPROVED** [review]
Very cool looking Tron vibe :sunglasses:

**Pull request merged**
